### PR TITLE
[FIX #206] Dynamically require commiteth.core in user namespace

### LINKED ISSUE #206: ClassNotFoundException during REPL startup
### Description
*Type*: <Bug>
*Summary*: running `lein repl` in a freshly initialized repo throws ClassNotFoundException.

#### Expected behavior
Get to the REPL prompt without any hassle.

#### Actual behavior
We get the below error:
```
Compiling 4 source files to /path-torepo/target/base+system+user+dev/classes
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: commiteth.eth.contracts.TokenReg, compiling:(commiteth/eth/token_registry.clj:1:1)
... and the stack trace follows.
```

### Solution
*Summary*: seems that `env/dev/clj/user.clj` is autoloaded by Clojure no matter what (see e.g. [this](https://github.com/technomancy/leiningen/issues/1787) and [this](https://www.reddit.com/r/Clojure/comments/5f2ctk/cant_compile_java_sources_with_lein_javac/dahrkw5/)). Afterwards it loads `token-registry` as one of its dependencies, which in turn imports generated Java classes.

Suggested resolution is to dynamically require `commiteth.core` in `user` ns (like suggested [here](https://groups.google.com/forum/#!topic/clojure/4ytDn6OHabI)).

### PR DESCRIPTION
**Pull request by siphiuel**
Dynamic require of `commiteth.core` allows us to skip autoloading of Java classes during running of lein tasks using `:dev` profile, as described in associated [issue](https://github.com/status-im/open-bounty/issues/206).

Also it seems that `:precomp` profile is not necessary anymore, as its sole purpose seems to  run `build-contracts` without auto-invoking `user.clj` compilation (as its `:source-paths` do not include `env/dev/clj/user.clj`).

### CODE REVIEW

**Comment by pablodip** [comment]
It's okay to me! Let's see what @tpatja thinks.

**Comment by tpatja** [comment]
Great finding @siphiuel!

File: env/dev/clj/user.clj [hunk 1]
```diff
@@ -1,13 +1,14 @@
...
+            [commiteth.figwheel :refer [start-fw stop-fw cljs]]))
 
 (defn start []
-  (mount/start-without #'commiteth.core/repl-server))
+  (require 'commiteth.core)
+  (mount/start-without (ns-resolve 'commiteth.core 'repl-server)))
 
 (defn stop []
-  (mount/stop-except #'commiteth.core/repl-server))
+  (require 'commiteth.core)
```
Comment (tpatja) [inline env/dev/clj/user.clj]: It should be enough to have the dynamic require in `start`

**Comment by siphiuel** [comment]
Thanks for reviewing!
