### PR TITLE
[FIX #226] Pagination: add cursor pointer for buttons, scroll to top

### LINKED ISSUE #226: UX details in pagination
- [ ] The cursor in the buttons should be a pointer.
- [ ] When moving to a different page the screen should probably be moved to the top of the list.
- [ ] The button of next and previous page should probably look disabled when the current page is the first and the last one respectively.
- [ ] When changing the tab from bounties to activity and viceversa the current page should probably be restarted, that is, always be 1, and right now it is maintained from previous state.
- [ ] The activity list should also probably show at the top the message "Showing X of X".
- [ ] It would probably help to have some style changes when hovering paging buttons.
- [ ] On Safari and FF clicking on page number redirects to random place on page.
Video: https://drive.google.com/open?id=1ZAHPgvmb1C7tuQmYR9-kx_hPVyHRjDc4
- [ ] Pagination should work on mobile, since right now the design is broken.

cc @denis-sharypin @siphiuel

### PR DESCRIPTION
**Pull request by siphiuel**
This will add cursor pointer when hovering over page navigation buttons. Also, now view will scroll upward when navigating to a different page.

Status: Finished.

### CODE REVIEW

**Comment by pablodip** [comment]
Is this finished or a WIP? Make sure to indicate it in the description, please. :)

Regarding the scrolling approach, I think we should do it through React, and it could be more advanced with a library like [react-scroll](https://github.com/fisshy/react-scroll) (which supports animations for example) or more simple by using just [refs](https://reactjs.org/docs/refs-and-the-dom.html). Just not sure how difficult would be to use react-scroll in Cljs.

**Comment by siphiuel** [comment]
@pablodip updated the description.

**Comment by siphiuel** [comment]
As to scrolling approach - not sure really which one to pick. `Element.scrollIntoView` does support animations as well, albeit not on all browsers.

**Comment by pablodip** [comment]
Agree with using `Element.scrollIntoView` for now. The main thing in the approach I think is to talk to the DOM through React: https://reactjs.org/docs/refs-and-the-dom.html

**Comment by siphiuel** [comment]
@pablodip thanks for suggestions! Made some changes, refs provide better locality, so no extra effect handlers needed.

**Comment by siphiuel** [comment]
Refactored refs-related code. There is now an additional component that subscribes to page number changes only.

File: src/cljs/commiteth/handlers.cljs [hunk 1]
```diff
@@ -64,19 +63,15 @@
...
- :set-active-page
- (fn [db [_ page]]
-   (assoc db :page page)))
-
-(reg-event-db
-  :set-bounty-page-number
+  :set-active-page
   (fn [db [_ page]]
-    (assoc db :bounty-page-number page)))
+    (assoc db :page page
```
Comment (pablodip) [inline src/cljs/commiteth/handlers.cljs]: What is `:page` used for?

File: src/cljs/commiteth/common.cljs [hunk 2]
```diff
@@ -30,9 +31,22 @@
 (defn issue-url [owner repo number]
   (str "https://github.com/" owner "/" repo "/issues/" number))
 
+(defn scroll-div [container-element]
```
Comment (pablodip) [inline src/cljs/commiteth/common.cljs]: Why exactly do we need this no-op component if we can just perform this behaviour in the list components?

File: src/cljs/commiteth/handlers.cljs (hunk 1 above)
Comment (siphiuel) [reply src/cljs/commiteth/handlers.cljs]: It's an active page keyword, e.g. `:bounties` or `:activity`.

File: src/cljs/commiteth/common.cljs (hunk 2 above)
Comment (siphiuel) [reply src/cljs/commiteth/common.cljs]: The idea was that list components might get updated during any page content changes, not just page number changes.

**Comment by siphiuel** [comment]
Disabled pointer cursor over active page buttons.

File: src/cljs/commiteth/handlers.cljs (hunk 1 above)
Comment (pablodip) [reply src/cljs/commiteth/handlers.cljs]: Yeah, sorry, I meant what is the difference between `:page` and `:page-number`, that both are being used here.

File: src/cljs/commiteth/common.cljs (hunk 2 above)
Comment (pablodip) [reply src/cljs/commiteth/common.cljs]: I've been thinking about when the scrolling should happen, and it is a little tricky.

The behaviour we are looking for is for the scrolling to trigger when the user navigates to a different page.

And it should not trigger in some other cases:

* As you said, when the list component updates for other reasons.
* And also when the page number changes for other reasons that are not the user navigating. For example, when changing the page, the page number is restarted, but the scrolling should not happen there. Or when the filters change, the page number is restarted as well, and the scrolling should not happen there either.

In order to get this I think the best thing is to pass the ref of the list to the children components so that the buttons where the clicks occur in the navigator have it, and trigger there the scrolling.

I think that is better because we trigger the scrolling exactly where we want it to happen, that is, when the user interacts with the navigator, and don't try to guess that behaviour from state changes in the page number.

File: src/cljs/commiteth/handlers.cljs (hunk 1 above)
Comment (siphiuel) [reply src/cljs/commiteth/handlers.cljs]: You're right - naming is slightly bad, `:page` should be `:tab` I guess. So it's confusing.

File: src/cljs/commiteth/common.cljs (hunk 2 above)
Comment (siphiuel) [reply src/cljs/commiteth/common.cljs]: Thanks for explaining! Just pushed an update.
